%%{init: {
  "theme": "base",
  "themeVariables": {
    "primaryColor": "#E0F2FE",
    "primaryTextColor": "#0B1020",
    "primaryBorderColor": "#0B1020",
    "lineColor": "#0B1020",
    "nodeBorder": "#0B1020"
  },
  "themeCSS": "svg{background:#ffffff}.edgePath path{stroke-width:3px!important}.node rect,.node circle{stroke-width:2.5px!important}.cluster rect{stroke-width:2.5px!important}" 
} }%%
graph TB
  subgraph kind-cluster
    subgraph ns:oms-dev
      IGW[Ingress] --> SVCGW[Service: gateway]
      SVCGW --> PODGW[(Deployment: gateway pods)]

      SVCORD[Service: orders] --> PODORD[(Deployment: orders pods)]
      STSDB[StatefulSet: postgres] --- PVCDB[(PVC)]

      subgraph Strimzi
        OP[Operator]
        BRK[(Kafka broker)]
      end

      %% Networking
      PODGW -->|gRPC| SVCORD
      PODORD <-->|produce/consume| BRK
      PODORD --> STSDB
    end
  end
