%%{init: {
  "theme": "base",
  "themeVariables": {
    "primaryColor": "#E0F2FE",
    "primaryTextColor": "#0B1020",
    "primaryBorderColor": "#0B1020",
    "lineColor": "#0B1020",
    "nodeBorder": "#0B1020"
  },
  "themeCSS": "svg{background:#ffffff}.edgePath path{stroke-width:3px!important}.edgeLabel{font-weight:700}.node rect,.node circle,.node ellipse{stroke-width:2.5px!important}.label text{font-weight:700}"
} }%%
graph LR
  %% Clients and Gateway
  C[Client Apps] -->|HTTP| GW[Gateway]

  %% Synchronous path
  GW -->|gRPC| ORD[Orders]

  %% Kafka bus
  K[(Kafka)]

  %% Services
  INV[Inventory]
  PAY[Payments]
  FUL[Fulfillment]

  %% Datastores
  ORDDB[(Postgres-Orders)]
  INVDB[(Postgres-Inventory)]
  PAYDB[(Postgres-Payments)]
  FULDB[(Fulfillment-DB)]

  %% Topics (labels on edges)
  ORD -->|publish oms.order.v1| K
  K -->|consume oms.order.v1| INV
  K -->|consume oms.order.v1| PAY

  INV -->|publish oms.inventory.v1| K
  PAY -->|publish oms.payment.v1| K
  K -->|consume oms.inventory.v1| ORD
  K -->|consume oms.payment.v1| ORD
  K -->|consume oms.order.v1 paid| FUL

  %% DB ownership
  ORD --- ORDDB
  INV --- INVDB
  PAY --- PAYDB
  FUL --- FULDB
